// <auto-generated />
using ElizaFlixAPI.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElizaFlixAPI.Migrations
{
    [DbContext(typeof(ConnectionContext))]
    [Migration("20240420190741_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElizaFlixAPI.DTO.Filme", b =>
                {
                    b.Property<string>("sigla")
                        .HasColumnType("text");

                    b.Property<string[]>("dir_Filmes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("dir_Thumb_Heid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dir_Thumb_Wid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("quantidade_eps")
                        .HasColumnType("integer");

                    b.Property<int>("tipo")
                        .HasColumnType("integer");

                    b.HasKey("sigla");

                    b.ToTable("filmes");
                });
#pragma warning restore 612, 618
        }
    }
}
