name: Pipeline CI/CD
run-name: Pipeline CI/CD executado por ${{ github.actor }} em ${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      - name: Execução do comando build
        working-directory: ./
        run: dotnet build ElizaFlixAPI.sln

  testes:
    needs: [build]
    uses: EduMss/ElizaFlixAPI-Pipeline/.github/workflows/testes.yml@master

  release:
    name: Criação de Release
    runs-on: ubuntu-latest
    needs: [testes]
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4
      - name: Efetuando o Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: |
            edumss/elizaflixapi:latest
            edumss/elizaflixapi:v${{github.run_number}}
        